sql_queries = [
  {
    "question": "What are the details of the top 10 most expensive products?",
    "sql_query": "SELECT TOP 10 ProductID, Name, ListPrice FROM SalesLT.Product ORDER BY ListPrice DESC;"
  },
  {
    "question": "How many orders have been placed in the current year?",
    "sql_query": "SELECT COUNT(*) AS TotalOrders FROM SalesLT.SalesOrderHeader WHERE YEAR(OrderDate) = YEAR(GETDATE());"
  },
  {
    "question": "What is the total sales amount for each customer?",
    "sql_query": "SELECT c.CustomerID, c.FirstName, c.LastName, SUM(soh.TotalDue) AS TotalSales FROM SalesLT.Customer c INNER JOIN SalesLT.SalesOrderHeader soh ON c.CustomerID = soh.CustomerID GROUP BY c.CustomerID, c.FirstName, c.LastName ORDER BY TotalSales DESC;"
  },
  {
    "question": "What are the top 5 products by sales quantity?",
    "sql_query": "SELECT TOP 5 p.Name, SUM(sod.OrderQty) AS TotalQuantity FROM SalesLT.SalesOrderDetail sod INNER JOIN SalesLT.Product p ON sod.ProductID = p.ProductID GROUP BY p.Name ORDER BY TotalQuantity DESC;"
  },
  {
    "question": "List the customers with their corresponding sales orders.",
    "sql_query": "SELECT c.CustomerID, c.FirstName, c.LastName, soh.SalesOrderID FROM SalesLT.Customer c INNER JOIN SalesLT.SalesOrderHeader soh ON c.CustomerID = soh.CustomerID ORDER BY c.CustomerID;"
  },
  {
    "question": "What is the average list price of products in each product category?",
    "sql_query": "SELECT pc.Name AS CategoryName, AVG(p.ListPrice) AS AverageListPrice FROM SalesLT.Product p INNER JOIN SalesLT.ProductCategory pc ON p.ProductCategoryID = pc.ProductCategoryID GROUP BY pc.Name ORDER BY AverageListPrice DESC;"
  },
  {
    "question": "Which products have not been sold in the last year?",
    "sql_query": "SELECT p.ProductID, p.Name FROM SalesLT.Product p LEFT JOIN SalesLT.SalesOrderDetail sod ON p.ProductID = sod.ProductID LEFT JOIN SalesLT.SalesOrderHeader soh ON sod.SalesOrderID = soh.SalesOrderID WHERE soh.OrderDate IS NULL OR YEAR(soh.OrderDate) < YEAR(GETDATE()) - 1;"
  },
  {
    "question": "How many products are there in each product category?",
    "sql_query": "SELECT pc.Name AS CategoryName, COUNT(p.ProductID) AS ProductCount FROM SalesLT.Product p INNER JOIN SalesLT.ProductCategory pc ON p.ProductCategoryID = pc.ProductCategoryID GROUP BY pc.Name ORDER BY ProductCount DESC;"
  },
  {
    "question": "What are the details of customers who have placed more than 5 orders?",
    "sql_query": "SELECT c.CustomerID, c.FirstName, c.LastName, COUNT(soh.SalesOrderID) AS OrderCount FROM SalesLT.Customer c INNER JOIN SalesLT.SalesOrderHeader soh ON c.CustomerID = soh.CustomerID GROUP BY c.CustomerID, c.FirstName, c.LastName HAVING COUNT(soh.SalesOrderID) > 5 ORDER BY OrderCount DESC;"
  },
  {
    "question": "What is the total revenue generated by each sales person?",
    "sql_query": "SELECT c.SalesPerson, SUM(soh.TotalDue) AS TotalRevenue FROM SalesLT.Customer c INNER JOIN SalesLT.SalesOrderHeader soh ON c.CustomerID = soh.CustomerID GROUP BY c.SalesPerson ORDER BY TotalRevenue DESC;"
  }
]